### ISSUE TITLE
error during dandiset download

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1017]
download appears to be successful, but threw this error in the end.

```bash
(base) MacBook-Pro-3:data bendichter$ dandi download DANDI:000008
PATH                                               SIZE       DONE             DONE% CHECKSUM STATUS          MESSAGE   
dandiset.yaml                                                                                 done            updated   
...0420-slice-2_cell-20180420-sample-2_icephys.nwb 9.3 MB     9.3 MB            100%    ok    done                      
...0420-slice-3_cell-20180420-sample-3_icephys.nwb 9.3 MB     9.3 MB            100%    ok    done                      
...            
...1003-slice-1_cell-20181003-sample-1_icephys.nwb 8.7 MB     8.7 MB            100%    ok    done                      
...1003-slice-3_cell-20181003-sample-3_icephys.nwb 8.8 MB     8.8 MB            100%    ok    done                      
...1003-slice-4_cell-20181003-sample-4_icephys.nwb 9.3 MB     9.3 MB            100%    ok    done                      
...1003-slice-2_cell-20181003-sample-2_icephys.nwb 9.3 MB     9.3 MB            100%    ok    done                      
Summary:                                           11.9 GB    11.9 GB                         1328 done       1 updated 
                                                              99.92%                          1 downloading             
                                                              ETA: 32 minutes                                           


ERROR: 1 asynchronous worker failed

Producing value for row ('sub-mouse-UWILU/sub-mouse-UWILU_ses-20181114-sample-2_slice-20181114-slice-1_cell-20181114-sample-2_icephys.nwb',) failed:
Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/connection.py", line 416, in connect
    self.sock = ssl_wrap_socket(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/dandi/download.py", line 645, in _download_file
    for block in downloader(dldir.offset):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/dandi/dandiapi.py", line 1292, in downloader
    result = self.client.session.get(url, stream=True, headers=headers)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

2022-05-19 19:26:14,509 [    INFO] Logs saved in /Users/bendichter/Library/Logs/dandi-cli/20220519225323Z-80015.log
```

**Comment by yarikoptic** [comment]
In summary it still said 1 downloading... Please rerun download to make sure you get all data. Please let us know if it does download anything

**Comment by jwodder** [comment]
@bendichter Is there anything to do for this issue?

**Comment by bendichter** [comment]
I'm testing with the latest now...

**Comment by bendichter** [comment]
I tried this again and got no error
