### ISSUE TITLE
downloading individual file works but throws an error

### ISSUE THREAD

**Issue by bendichter** [dandi/dandi-cli#1025]
I am using the following to use the dandi cli to download an individual file

```bash
dandi download https://dandiarchive.org/dandisets/000053/versions/"draft"/assets/?path="sub-npJ3/sub-npJ3_ses-20190504_behavior.nwb"
```

which works (and is very fast). The correct file is downloaded to my cwd, and is intact. However, the command throws an error:

```pytb
Producing value for row ('sub-npJ3_ses-20190504_behavior.nwb/.',) failed:
Traceback (most recent call last):
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 438, in result
    return self.__get_result()
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/Users/bendichter/opt/miniconda3/lib/python3.9/site-packages/dandi/download.py", line 711, in _download_file
    os.utime(path, (time.time(), ensure_datetime(mtime).timestamp()))
NotADirectoryError: [Errno 20] Not a directory
```

Am I using this command correctly?

**Comment by jwodder** [comment]
@bendichter Can you post the logs for the download session (preferrably as a gist)?  On macOS, they are located in `~/Library/logs/dandi-cli`.

**Comment by bendichter** [comment]
https://gist.github.com/bendichter/25dfdcf75cc1ede9e86c6cd57f3052ce

**Comment by yarikoptic** [comment]
lovely ... Given that `.../assets/?path={path}` could indeed point to **any** portion within real `{path}`, and results would not include "folders", It feels that we need to become "smarty pants" of some kind here.  What if we just strip away `Path(path).parent` here, i.e. for asset with path `f` it would be `{f[len(op.dirname(f)):]}`?

here is some experimentation -- seems to be sensible:

```
In [39]: path='/a/b'; print(f"path={path}")
path=/a/b

In [40]: for f in ['.nwb', '/c', '/a.nwb']: fp=f"{path}{f}".replace('//','/'); print(f"asset {fp} -> {fp[len(op.dirname(path)):].lstrip('/')}")
asset /a/b.nwb -> b.nwb
asset /a/b/c -> b/c
asset /a/b/a.nwb -> b/a.nwb
```
so if `b` is really a folder -- we would get that folder locally.  But if `b` is a folder and `{path}` has trailing `/`:

```
In [41]: path='/a/b/'; print(f"path={path}")
path=/a/b/

In [42]: for f in ['.nwb', '/c', '/a.nwb']: fp=f"{path}{f}".replace('//','/'); print(f"asset {fp} -> {fp[len(op.dirname(path)):].lstrip('/')}")
asset /a/b/.nwb -> .nwb
asset /a/b/c -> c
asset /a/b/a.nwb -> a.nwb
```

similarly to `rsync` we would get its content in curdir.  And just a test for "top level":

```
In [43]: path='/'; print(f"path={path}")
path=/

In [44]: for f in ['.nwb', '/c', '/a.nwb']: fp=f"{path}{f}".replace('//','/'); print(f"asset {fp} -> {fp[len(op.dirname(path)):].lstrip('/')}")
asset /.nwb -> .nwb
asset /c -> c
asset /a.nwb -> a.nwb
```

**Comment by bendichter** [comment]
thanks guys!
