### ISSUE TITLE
dandi download had two weird states

### ISSUE THREAD

**Issue by satra** [dandi/dandi-cli#1030]
`dandi download DANDI:000243` executed on dandihub

failed partly in instance 1 because it couldn't acquire a lock. seems like it didn't wait at all.

<details> <summary> error details </summary>

```
PATH                              SIZE      DONE           DONE% CHECKSUM STATUS          MESSAGE   
dandiset.yaml                                                             done            updated   
participants.tsv                  26 Bytes  26 Bytes        100%    ok    done                      
sub-S01/anat/sub-S01_T2w.json     311 Bytes 311 Bytes       100%    ok    done                      
sub-S01/anat/sub-S01_T2w.nii.gz   3.1 GB    3.1 GB          100%    ok    done                      
dataset_description.json          263 Bytes 263 Bytes       100%    ok    done                      
sub-S01/anat/sub-S01_T2w.ome.zarr 3.0 GB    2.5 GB           99%          downloading     896 done  
Summary:                          6.1 GB    5.6 GB                        5 done          1 updated 
                                            91.50%                        1 downloading   1 896 done
                                            ETA: 3 minutes                                          


ERROR: 1 asynchronous worker failed

Producing value for row ('sub-S01/anat/sub-S01_T2w.ome.zarr',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 380, in get
    r = self._funnel.get(block=block, timeout=timeout)
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 223, in get
    raise EndOfInputError()
interleave.EndOfInputError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 841, in _download_zarr
    for path, status in it:
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 348, in __next__
    return self.get()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 382, in get
    self._end()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 402, in _end
    e.get()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 112, in get
    raise e.with_traceback(tb)
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 276, in _process
    x = next(it)
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 902, in pairing
    for d in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 631, in _download_file
    with DownloadDirectory(path, digests or {}) as dldir:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 736, in __enter__
    raise RuntimeError(f"Could not acquire download lock for {self.filepath}")
RuntimeError: Could not acquire download lock for 000243/sub-S01/anat/sub-S01_T2w.ome.zarr/0/0/0/6/4/7
```
</details>

failed in instance two with this message: 

<details>
<summary> error details </summary>

```
PATH                              SIZE    DONE    DONE% CHECKSUM STATUS    MESSAGE    
dandiset.yaml                                                    skipped   no change  
participants.tsv                                                                      
sub-S01/anat/sub-S01_T2w.json                                                         
sub-S01/anat/sub-S01_T2w.nii.gz                                                       
dataset_description.json                                                              
sub-S01/anat/sub-S01_T2w.ome.zarr                                                     
Summary:                          0 Bytes 0 Bytes                1 skipped 1 no change
                                  +6.1 GB 0.00%                                       


ERROR: 5 asynchronous workers failed

Producing value for row ('participants.tsv',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 521, in _download_file
    raise FileExistsError(f"File {path!r} already exists")
FileExistsError: File './000243/participants.tsv' already exists

Producing value for row ('sub-S01/anat/sub-S01_T2w.json',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 521, in _download_file
    raise FileExistsError(f"File {path!r} already exists")
FileExistsError: File './000243/sub-S01/anat/sub-S01_T2w.json' already exists

Producing value for row ('sub-S01/anat/sub-S01_T2w.nii.gz',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 521, in _download_file
    raise FileExistsError(f"File {path!r} already exists")
FileExistsError: File './000243/sub-S01/anat/sub-S01_T2w.nii.gz' already exists

Producing value for row ('dataset_description.json',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 521, in _download_file
    raise FileExistsError(f"File {path!r} already exists")
FileExistsError: File './000243/dataset_description.json' already exists

Producing value for row ('sub-S01/anat/sub-S01_T2w.ome.zarr',) failed:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 380, in get
    r = self._funnel.get(block=block, timeout=timeout)
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 223, in get
    raise EndOfInputError()
interleave.EndOfInputError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 279, in _print_async_exceptions
    future.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/lib/python3.9/site-packages/pyout/interface.py", line 482, in async_fn
    for i in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 841, in _download_zarr
    for path, status in it:
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 348, in __next__
    return self.get()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 382, in get
    self._end()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 402, in _end
    e.get()
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 112, in get
    raise e.with_traceback(tb)
  File "/opt/conda/lib/python3.9/site-packages/interleave/__init__.py", line 276, in _process
    x = next(it)
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 902, in pairing
    for d in gen:
  File "/opt/conda/lib/python3.9/site-packages/dandi/download.py", line 521, in _download_file
    raise FileExistsError(f"File {path!r} already exists")
FileExistsError: File './000243/sub-S01/anat/sub-S01_T2w.ome.zarr/.zattrs' already exists
```
</details>

**Comment by yarikoptic** [comment]
> @satra I suspect the first error was due to some sort of filesystem hiccup.

@satra , if issue repeatable then may be with our `.dandidownload/` extra directory we manage to reach some MAX_PATH length or smth... if it is just flaky behavior, may be would need to try a few times with sleeps @jwodder since it is also not nice UX whenever a tool just freaks out like that

> The second error is because dandi download defaults to --existing=error, and the "existing" setting gets applied to individual files of Zarrs.

@jwodder but those exceptions should not be thrown in the user's face -- they should be reflected in pyout output in "message" that file exists, as I believe used to happen.  I think somewhere catching of those exceptions for pyout display has changed so exceptions started to bubble up instead of being reflected in pyout rendering.
