### ISSUE TITLE
Make any .request authenticate if 401?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#1137]
https://github.com/dandi/dandi-cli/pull/1132 solved problem for `ls` but in the course of going through https://github.com/dandi/dandi-cli/issues/1134 I got similar issue of dandi-cli not authenticating for `get_asset_by_path`:

```
❯ dandi --version
0.46.4+10.gef9d853
❯ cat embargo_url.py
from dandi.dandiapi import DandiAPIClient
import sys
dandiset_id = sys.argv[1] or '000006'  # ephys dataset from the Svoboda Lab
filepath = sys.argv[2] or 'sub-anm372795/sub-anm372795_ses-20170718.nwb'  # 450 kB file
with DandiAPIClient() as client:
    # client.dandi_authenticate()
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
    s3_url = asset.get_content_url(follow_redirects=1, strip_query=True)
    print(f"{dandiset_id}/{filepath} has {s3_url}")
❯ python embargo_url.py '000344' 'sub-private/sub-private.dat'
Error 401 while sending GET request to https://api.dandiarchive.org/api/dandisets/000344/versions/draft/assets/: {"detail":"Authentication credentials were not provided."}
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/trash/embargo_url.py", line 7, in <module>
    asset = client.get_dandiset(dandiset_id, 'draft').get_asset_by_path(filepath)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 1106, in get_asset_by_path
    (asset,) = (
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 1106, in <genexpr>
    (asset,) = (
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 1062, in get_assets_with_path_prefix
    for a in self.client.paginate(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 354, in paginate
    resp = self.get(path, params=params, json_resp=False)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 300, in get
    return self.request("GET", path, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiapi.py", line 272, in request
    raise requests.HTTPError(msg, response=result)
requests.exceptions.HTTPError: Error 401 while sending GET request to https://api.dandiarchive.org/api/dandisets/000344/versions/draft/assets/: {"detail":"Authentication credentials were not provided."}
```

I think that we should aim to `dandi_authenticate` for any `.request` if we get 401 , shouldn't we?

**Comment by jwodder** [comment]
@yarikoptic I disagree.  If a user is using the Python API as a library, calling a request method when they've failed to call `dandi_authenticate()` beforehand should not suddenly lead to an interactive prompt or poking about for keyrings on the filesystem.

**Comment by yarikoptic** [comment]
hm, ok, let's keep it at that then for now, although we might reconsider
