### ISSUE TITLE
installation (pip install) might not work

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#12]
reporting the failure to install on our test aws ec2 box:
```shell
yoh@ip-172-31-33-190:~$ git clone https://github.com/dandi/dandi-cli && cd dandi-cli &&  virtualenv --system-site-packages --python=python3 venvs/dev3 && source venvs/dev3/bin/activate && pip install -e .
Cloning into 'dandi-cli'...
remote: Enumerating objects: 113, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (75/75), done.
remote: Total 113 (delta 56), reused 84 (delta 34), pack-reused 0
Receiving objects: 100% (113/113), 40.93 KiB | 10.23 MiB/s, done.
Resolving deltas: 100% (56/56), done.
Already using interpreter /usr/bin/python3
Using base prefix '/usr'
New python executable in /home/yoh/dandi-cli/venvs/dev3/bin/python3
Also creating executable in /home/yoh/dandi-cli/venvs/dev3/bin/python
Installing setuptools, pkg_resources, pip, wheel...done.
Obtaining file:///home/yoh/dandi-cli
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/yoh/dandi-cli/venvs/dev3/bin/python3 /home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprj7_0raa
       cwd: /home/yoh/dandi-cli
  Complete output (10 lines):
  Traceback (most recent call last):
    File "/home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 48, in get_requires_for_build_wheel
      backend = _build_backend()
    File "/home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 39, in _build_backend
      obj = getattr(obj, path_part)
  AttributeError: module 'setuptools.build_meta' has no attribute '__legacy__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/yoh/dandi-cli/venvs/dev3/bin/python3 /home/yoh/dandi-cli/venvs/dev3/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmprj7_0raa Check the logs for full command output.

(dev3) yoh@ip-172-31-33-190:~/dandi-cli$ apt-cache policy python3-setuptools
python3-setuptools:
  Installed: 39.0.1-2
  Candidate: 39.0.1-2
  Version table:
 *** 39.0.1-2 500
        500 http://us-east-2.ec2.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by yarikoptic** [comment]
https://github.com/pypa/setuptools/issues/1694 suggests a workaround, will test now and push a fix if that works

**Comment by yarikoptic** [comment]
ok - workaround pushed in a7b179ff1e451f4fd84b525aaeaa118fd465d0e0

but then runs into a still open https://github.com/warner/python-versioneer/issues/192 with versioneer issue, worked around now in dd49a40afa32c6426f464233196cf4a27ab1dea8.

Both pushed, the original issue is resolved
