### ISSUE TITLE
UX: provide UI to allow reenter the key if permission is denied

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#128]
in our case with @mgrauer was a local dandi instance with probably an outdated API key

**Comment by yarikoptic** [comment]
possibly related fiasco during introducing locking:

<details>
<summary>locking (but not authorization) fails</summary> 

```shell
$> DANDI_DEVEL=1 dandi upload -i local-docker --validation ignore sub-759711149/sub-759711149.nwb
2020-07-08 17:39:56,523 [    INFO] Found 1 files to consider
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/dandi", line 11, in <module>
    load_entry_point('dandi', 'console_scripts', 'dandi')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/command.py", line 118, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_upload.py", line 582, in upload
    with out, \
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/girder.py", line 446, in lock_dandiset
    resp = self.post(f'dandi/{dandiset_identifier}/lock')
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/lib/python3.8/site-packages/girder_client/__init__.py", line 494, in post
    return self.sendRestRequest('POST', path, parameters, files=files,
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/lib/python3.8/site-packages/girder_client/__init__.py", line 479, in sendRestRequest
    raise HttpError(
girder_client.HttpError: HTTP error 401: POST http://localhost:8091/api/v1/dandi/000027/lock
Response text: {"message": "You must be logged in.", "type": "access"}

```
</details>
