### ISSUE TITLE
unable to upload [WinError 10060]

### ISSUE THREAD

**Issue by phildong** [dandi/dandi-cli#1386]
I'm trying to upload a dataset using dandi cli on windows and getting the following error:

```
2023-12-30T13:14:27-0500 [ERROR   ] dandi 9428:11692 HTTP connection failed
Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 404, in _make_request
    self._validate_conn(conn)
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 1058, in _validate_conn
    conn.connect()
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
                ^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\util\ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\ssl.py", line 517, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\ssl.py", line 1108, in _create
    self.do_handshake()
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\ssl.py", line 1379, in do_handshake
    self._sslobj.do_handshake()
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 799, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\util\retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 715, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 407, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\urllib3\connectionpool.py", line 358, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='dandiarchive.s3.amazonaws.com', port=443): Read timed out. (read timeout=None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\dandi\dandiapi.py", line 199, in request
    for i, attempt in enumerate(
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\tenacity\__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\tenacity\__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\dandi\dandiapi.py", line 214, in request
    result = self.session.request(
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\anaconda3\envs\nwb\Lib\site-packages\requests\adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='dandiarchive.s3.amazonaws.com', port=443): Read timed out. (read timeout=None)
```

I have no clue how to debug this since it looks like a connection/server error. Any suggestion would be helpful. Thank you!

**Comment by kabilar** [comment]
Hi @phildong, thank you for the report.  Could you please provide the commands you are using to organize and upload your Dandiset?  (Perhaps I missed it in the traceback above.)

**Comment by yarikoptic** [comment]
datestamp is 2023-12-30T13:14:27-0500 -- which is exactly around the time point I think there were some odd connection issues for 2 hours -- our dump of heroku logs was empty... could you please retry and report back?

**Comment by yarikoptic** [comment]
I will assume it was due to that connectivity issue. Please reopen if it is not so
