### ISSUE TITLE
ResourceWarning while running tests

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#212]
```shell
$> python -m pytest -s -v -k test_upload dandi
================================================= test session starts ==================================================
platform linux -- Python 3.8.5, pytest-4.6.9, py-1.8.1, pluggy-0.13.0 -- /home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('/home/yoh/proj/dandi/dandi-cli/.hypothesis/examples')
rootdir: /home/yoh/proj/dandi/dandi-cli, inifile: tox.ini
plugins: mock-3.2.0, cov-2.10.0, xdist-1.32.0, timeout-1.3.3, forked-1.1.3, hypothesis-4.36.2
collecting ... Exception ignored in: <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 582, in _compile_bytecode
ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Exception ignored in: <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3320, in streamline
    super(ParseExpression,self).streamline()
ResourceWarning: unclosed <socket.socket fd=5, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Exception ignored in: <socket.socket fd=6, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3320, in streamline
    super(ParseExpression,self).streamline()
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Exception ignored in: <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/lib/python3.8/site-packages/pkg_resources/_vendor/pyparsing.py", line 3320, in streamline
    super(ParseExpression,self).streamline()
ResourceWarning: unclosed <socket.socket fd=7, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/47521/bus>
collected 73 items / 69 deselected / 4 selected    
```

@jwodder - any ideas? do you see those?

**Comment by jwodder** [comment]
I'm seeing slightly different (and fewer) warnings.  I think they started some time last week:

```
Exception ignored in: <ssl.SSLSocket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.15', 57833), raddr=('3.19.164.171', 443)>
ResourceWarning: unclosed <ssl.SSLSocket fd=14, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('10.0.0.15', 57833), raddr=('3.19.164.171', 443)>
```

**Comment by nottrobin** [comment]
Ever get to the bottom of this? I have the same problem.

**Comment by yarikoptic** [comment]
hm, I don't think I saw those recently.  @nottrobin could you provide a bit more detail on your setup -- version of python, requests library, and OS (pretty much that "platform" line you see in output of pytest)?
