### ISSUE TITLE
Changes in dandi-publish broke downloader

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#228]
```shell
$> dandi --pdb -l debug download -f debug https://dandiarchive.org/dandiset/000027/0.200721.2222
2020-09-02 18:04:53,725 [   DEBUG] Running a newer version (0.6.2+57.g00414f5) of dandi/dandi-cli than available (0.6.1)
2020-09-02 18:04:53,833 [   DEBUG] Parsing url https://dandiarchive.org/dandiset/000027/0.200721.2222
2020-09-02 18:04:54,444 [   DEBUG] Parsing url https://gui.dandiarchive.org/#/dandiset/000027/0.200721.2222
2020-09-02 18:04:54,451 [   DEBUG] Parsed into ('api', 'https://publish.dandiarchive.org/api/', 'dandiset', {'dandiset_id': '000027', 'version': '0.200721.2222'})
2020-09-02 18:04:54,452 [    INFO] Traversing 000027 (version: 0.200721.2222)
2020-09-02 18:04:54,718 [ WARNING] Got completely empty metadata record for dandiset, not producing dandiset.yaml
2020-09-02 18:04:54,798 [   DEBUG] Caught exception Invalid isoformat string: '2020-07-21T22:22:16.882641Z'
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli/venvs/dev3/bin/dandi", line 11, in <module>
    load_entry_point('dandi', 'console_scripts', 'dandi')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/base.py", line 106, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_download.py", line 95, in download
    return download.download(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/download.py", line 317, in download
    for rec in gen_:
  File "/home/yoh/proj/dandi/dandi-cli/dandi/download.py", line 471, in download_generator
    for resp in _download_generator:
  File "/home/yoh/proj/dandi/dandi-cli/dandi/download.py", line 697, in _download_file
    if is_same_time(stat.st_mtime, mtime):
  File "/home/yoh/proj/dandi/dandi-cli/dandi/utils.py", line 114, in is_same_time
    norm_times = [
  File "/home/yoh/proj/dandi/dandi-cli/dandi/utils.py", line 115, in <listcomp>
    ensure_datetime(t, strip_tzinfo=strip_tzinfo, tz=datetime.timezone.utc)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/utils.py", line 175, in ensure_datetime
    t = fromisoformat(t)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/utils.py", line 155, in fromisoformat
    return datetime.datetime.fromisoformat(t)
ValueError: Invalid isoformat string: '2020-07-21T22:22:16.882641Z'

> /home/yoh/proj/dandi/dandi-cli/dandi/utils.py(155)fromisoformat()
-> return datetime.datetime.fromisoformat(t)
```

PS I have "released" 0.6.2 on github now, so etelemetry should become happy again

edit: report against `dandi-publish` : https://github.com/dandi/dandi-publish/issues/145

**Comment by yarikoptic** [comment]
was fixed by #229
