### ISSUE TITLE
local_docker_compose some times fails

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#245]
e.g. this run of master: https://github.com/dandi/dandi-cli/runs/1144609727

it seems that the initial failure causing it is

`minio.error.InvalidAccessKeyId: InvalidAccessKeyId: message: The access key Id you provided does not exist in our records.`

<details>
<summary>more of traceback etc</summary> 

```shell
Creating dandiarchive-docker_django_run ... done
Traceback (most recent call last):
  File "./manage.py", line 20, in <module>
    main()
  File "./manage.py", line 16, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.8/site-packages/django/apps/registry.py", line 114, in populate
    app_config.import_models()
  File "/usr/local/lib/python3.8/site-packages/django/apps/config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
...
  File "/opt/django/dandi/publish/models/asset.py", line 27, in _get_asset_blob_storage
    return create_s3_storage(settings.DANDI_DANDISETS_BUCKET_NAME)
  File "/opt/django/dandi/publish/storage.py", line 119, in create_s3_storage
    storage = VerbatimNameMinioStorage(
  File "/opt/django/dandi/publish/storage.py", line 57, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/minio_storage/storage.py", line 75, in __init__
    self._init_check()
  File "/usr/local/lib/python3.8/site-packages/minio_storage/storage.py", line 89, in _init_check
    if self.auto_create_bucket and not self.client.bucket_exists(
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 404, in bucket_exists
    self._url_open('HEAD', bucket_name=bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2185, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2063, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "/usr/local/lib/python3.8/site-packages/minio/api.py", line 2105, in _get_bucket_location
    raise ResponseError(response, method, bucket_name).get_exception()
minio.error.InvalidAccessKeyId: InvalidAccessKeyId: message: The access key Id you provided does not exist in our records.
Stopping dandiarchive-docker_rabbitmq_1 ... 
Stopping dandiarchive-docker_postgres_1 ... 
```
</details>

which overall leads to `87 passed, 13 errors`.  If that is the actual issue triggering the failure -- smells like some race condition, and may be then should be addressed at "-publish" level.  Or could we just try starting a few times within our fixture?  WDYT @jwodder ?

**Comment by jwodder** [comment]
I think we should begin by filing an issue with dandi-publish and seeing what underlying cause they identify.

**Comment by yarikoptic** [comment]
would you be so kind to follow up on `dandi-publish` @jwodder about this?

**Comment by jwodder** [comment]
Issue created: https://github.com/dandi/dandi-publish/issues/157

**Comment by yarikoptic** [comment]
@jwodder -- don't you think if we add a few retries in the fixture to do `compose up` with some random (up to 60 sec) sleep upon failure would help to mitigate? if you see it viable -- please implement that

**Comment by jwodder** [comment]
@yarikoptic I added healthchecks to the commonly-failing containers instead: #272

**Comment by yarikoptic** [comment]
so let's consider this one done!
