### ISSUE TITLE
migrate2newschema: two exceptions on existing datasets

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#328]
from a complete script setup: https://github.com/dandi/dandi-api-datasets

```shell
(git-annex)lena:~/proj/dandi/dandi-api-datasets[master]git-annex
$> cat 000010/EXCEPTION
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-api-datasets/tools/populate_dandiset_yaml.py", line 28, in <module>
    new_meta = migrate2newschema(dandiset_meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 517, in migrate2newschema
    newmeta = convertv1(meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 436, in convertv1
    if item in val.values():
AttributeError: 'Resource' object has no attribute 'values'
```

```shell
$> cat 000041/EXCEPTION 
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-api-datasets/tools/populate_dandiset_yaml.py", line 28, in <module>
    new_meta = migrate2newschema(dandiset_meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 517, in migrate2newschema
    newmeta = convertv1(meta)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 478, in convertv1
    value["maximum"] = float(value["maximum"].split()[0])
ValueError: could not convert string to float: '3-7'
```

**Comment by jwodder** [comment]
@yarikoptic I believe I've fixed the first exception.  I'm guessing that the second exception is caused by a `"maximum"` field being of the form "`3-7 days`" or similar; how should that be handled?

**Comment by yarikoptic** [comment]
I think probably we should deal only with the first one in the dandi-cli.

@bendichter @codycbakerphd in https://gui.dandiarchive.org/#/dandiset/000041 we have odd maximum/minimum for age.  I think it should just be fixed in the dandiset's metadata on dandiarchive.

**Comment by CodyCBakerPhD** [comment]
@yarikoptic Unable to edit that field of the metadata yml on the archive. Maybe you have to do the surgery on it?

**Comment by yarikoptic** [comment]
hm, fun ;)  Thank you @CodyCBakerPhD . But would I be right to assume it is min 3 and maximum 7 and units days?
