### ISSUE TITLE
upload: choked while uploading lots of tiny files

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#502]
did
```
drogon:/mnt/backup/dandi/trash/010000
$> DANDI_DEVEL=1 dandi --pdb upload --validation ignore --allow-any-path -i dandi-api sub-*

```
to upload 1mil files (ref: https://github.com/dandi/dandi-api/issues/78#issuecomment-806714079)

which fell into pdb and was not clear what exactly the reason
<details>
<summary>copy paste from screen with some traceback</summary> 

```shell
sub-1/sub-1_ses-3_cell-5.z/8    29 Bytes         2               100% uploading
sub-1/sub-1_ses-3_cell-5.z/6    29 Bytes         2               100% producing asset
sub-1/sub-1_ses-3_cell-5.z/10   30 Bytes         2                    extracting metadata
                                                                      3 uploading
                                                                      1 producing asset
2021-03-25 12:59:22,409 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210325162907Z-21350.log
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/dandi-devel/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/base.py", line 109, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_upload.py", line 98, in upload
    upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 49, in upload
    return _new_upload(
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 907, in _new_upload
    out(rec)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 96, in wrapped
    return method(self, *args, **kwds)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 634, in __call__
    self._write(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 357, in _write
    self._write_fn(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 376, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/common.py", line 939, in update
    summ_rows = self.summary.summarize(
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/summary.py", line 53, in summarize
    summaries[col] = agg_fn(list(colvals))
  Filesub-1/sub-1_ses-3_cell-5.z/6    29 Bytes         2               100% done
    total = sum(v["size"] for v in uploaded_paths.values())
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in <genexpr>
sub-1/sub-1_ses-3_cell-5.z/11   30 Bytes         2                    pre-validating
sub-1/sub-1_ses-3_cell-5.z/9    29 Bytes         2                    calculating etag

> /home/yoh/proj/dandi/dandi-cli/dandi/upload.py(869)<genexpr>()
-> total = sum(v["size"] for v in uploaded_paths.values())
2021-03-25 12:59:22,716 [   ERROR] Error 404 while sending POST request to https://api.dandiarchive.org/api/blobs/digest/: {"detail":"Not found."}
Summary:                        72.4 kB   2411 with errors 40 Bytes/s 2405 done
                                                                      3 uploading
                                                                      1 calculating etag
                                                                      1 extracting metadata
                                                                      1 pre-validating
                                                                      1 digesting
2021-03-25 12:59:22,757 [   ERROR] Error 404 while sending POST request to https://api.dandiarchive.org/api/blobs/digest/: {"detail":"Not found."}
2021-03-25 12:59:22,763 [   ERROR] Error 404 while sending POST request to https://api.dandiarchive.org/api/blobs/digest/: {"detail":"Not found."}
2021-03-25 12:59:22,895 [   ERROR] Error 404 while sending POST request to https://api.dandiarchive.org/api/blobs/digest/: {"detail":"Not found."}
2021-03-25 12:59:23,230 [    INFO] sub-1/sub-1_ses-3_cell-5.z/7: Asset successfully uploaded
2021-03-25 12:59:23,316 [    INFO] sub-1/sub-1_ses-3_cell-5.z/8: Asset successfully uploaded
2021-03-25 12:59:23,752 [    INFO] sub-1/sub-1_ses-3_cell-5.z/10: Asset successfully uploaded
2021-03-25 12:59:23,865 [    INFO] sub-1/sub-1_ses-3_cell-5.z/11: Asset successfully uploaded
2021-03-25 12:59:23,924 [    INFO] sub-1/sub-1_ses-3_cell-5.z/12: Asset successfully uploaded
2021-03-25 12:59:23,987 [    INFO] sub-1/sub-1_ses-3_cell-5.z/9: Asset successfully uploaded
(Pdb) bt

```
</details>
and I have not looked into server logs. `dandi-cli` was 0.12.0+17.gbfe168c ... I will update `dandi-cli` to 0.12.1 and see if reproduces (although we switched from checking blobs for presence so it might just hide away the issue with dandi-api)

**Comment by yarikoptic** [comment]
I think this might be the reason:
```
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/summary.py", line 53, in summarize
    summaries[col] = agg_fn(list(colvals))
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in upload_agg
    # with upload etc
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in <genexpr>
    # with upload etc
RuntimeError: dictionary changed size during iteration
```
relating to traceback in original post:
```
    total = sum(v["size"] for v in uploaded_paths.values())
```

I will try by making first a copy of `uploaded_paths.values()`.  I bet this also points to suboptimal code for dealing with 1mil files upload. And we might not be able to avoid some locking or prepopulating `uploaded_paths` so dictionary itself would not change

<details>
<summary>full traceback etc</summary> 

```shell
Traceback (most recent call last):
  File "/home/yoh/miniconda3/envs/dandi-devel/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/base.py", line 109, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli/dandi/cli/cmd_upload.py", line 98, in upload
    validation="require",
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 49, in upload
    if instance.girder is None:
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 907, in _new_upload
    rec[tuple(rec_fields[1:])] = process_path(path, relpath)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 96, in wrapped
    return method(self, *args, **kwds)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 634, in __call__
    self._write(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 357, in _write
    self._write_fn(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/interface.py", line 376, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/common.py", line 939, in update
    summ_rows = self.summary.summarize(
  File "/home/yoh/miniconda3/envs/dandi-devel/lib/python3.8/site-packages/pyout/summary.py", line 53, in summarize
    summaries[col] = agg_fn(list(colvals))
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in upload_agg
    # with upload etc
  File "/home/yoh/proj/dandi/dandi-cli/dandi/upload.py", line 869, in <genexpr>
    # with upload etc
RuntimeError: dictionary changed size during iteration

```
</details>
