### ISSUE TITLE
Cannot upload file

### ISSUE THREAD

**Issue by gmazzamuto** [dandi/dandi-cli#529]
Dear developers,

I am experiencing some difficulties with uploading files to DANDI. I am using `dandi==0.12.1` on Ubuntu Server 20.04 LTS. With the `dandiset.yaml` properly in place and having exported `DANDI_API_KEY`, I get the following error whith `dandi upload`:
```
Error: Failed to lock dandiset 000026 due to: You must be logged in.
```
Thank you for your help!

**Comment by yarikoptic** [comment]
`DANDI_API_KEY` is for the new archive.  To upload to "official" archive it should have been `DANDI_GIRDER_API_KEY` but that is AFAIK a "hidden knowledge" -- `dandi` should have just asked for the key, didn't it?  If it doesn't -- it is something for us to fix (please run as `DANDI_DEVEL=1 dandi -l debug upload --devel-debug` and shared output may be via email debian@onerussian.com if you spot any secrets - might help).  As a temporary test/workaround -- try to specify key in the `DANDI_GIRDER_API_KEY` env var

**Comment by yarikoptic** [comment]
As @satra's question pointed out -- it indeed used to be `DANDI_API_KEY` but since not widely advocated for use, it was renamed  to that `DANDI_GIRDER_API_KEY` in 0.11.0 to prepare for transition to the new server

**Comment by gmazzamuto** [comment]
I tried also with `DANDI_GIRDER_API_KEY` but it's still not working. This time however I was asked for the API key and to create a keyring. But again not working. Here is the stack trace:

```
Traceback (most recent call last):
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/dandi/girder.py", line 535, in lock_dandiset
    resp = self.post(f"dandi/{dandiset_identifier}/lock")
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/girder_client/__init__.py", line 478, in post
    return self.sendRestRequest('POST', path, parameters, files=files,
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/girder_client/__init__.py", line 463, in sendRestRequest
    raise HttpError(
girder_client.HttpError: HTTP error 401: POST https://girder.dandiarchive.org/api/v1/dandi/000026/lock
Response text: {"message": "You must be logged in.", "type": "access"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/venv_dandi/bin/dandi", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/dandi/cli/base.py", line 109, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/dandi/cli/cmd_upload.py", line 98, in upload
    upload(
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/dandi/upload.py", line 556, in upload
    with out, client.lock_dandiset(dandiset.identifier):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ubuntu/venv_dandi/lib/python3.8/site-packages/dandi/girder.py", line 539, in lock_dandiset
    raise LockingError(
dandi.exceptions.LockingError: Failed to lock dandiset 000026 due to: You must be logged in.
```

**Comment by yarikoptic** [comment]
sorry for my short memory -- this is a lingering issue with repectfully old accounts on dandiarchive's girder server, which require regeneration of the key.  Here is the https://github.com/dandi/dandi-cli/issues/238#issuecomment-693478473 on how to regenerate the key (so you get "Full scope") and should be able to upload.  Please reopen if issue persists
