### ISSUE TITLE
fixup extraction of digest?

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#547]
just spotted in https://github.com/dandi/dandi-api-datasets/blob/master/000013/CONVERSION.errors been flooded with:

```
sub-anm226694/sub-anm226694_ses-20140222_obj-1noi7y3_behavior+icephys+ogen.nwb
Traceback (most recent call last):
  File "tools/populate_dandiset_asset_yamls.py", line 64, in main
    metadata = nwb2asset(
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 330, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 379, in metadata2asset
    return extract_model(models.BareAssetMeta, metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 234, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 303, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/dandi/cronlib/dandi-api-datasets/.cronlib/venv/lib/python3.8/site-packages/dandi/metadata.py", line 283, in extract_digest
    return {models.DigestType[metadata["digest_type"]]: metadata["digest"]}
  File "/home/dandi/miniconda3/lib/python3.8/enum.py", line 344, in __getitem__
    return cls._member_map_[name]
KeyError: 'sha256'
```

I guess this code path isn't tested and doesn't account for recent change in model on how digests are stored now?

**Comment by jwodder** [comment]
@yarikoptic This is because I missed a spot in https://github.com/dandi/dandi-api-datasets/pull/28; this PR fixes that: https://github.com/dandi/dandi-api-datasets/pull/29.

**Comment by yarikoptic** [comment]
merged that PR, let's hope it resolves it , thank you!
