### ISSUE TITLE
Error during dandi upload

### ISSUE THREAD

**Issue by CodyCBakerPhD** [dandi/dandi-cli#566]
@yarikoptic @satra 

Trying to upload Loren Franks data with all the hdmf/pynwb fixes, and it's passing validation but final upload gives this traceback (with the --pdb flag, just says `Error: 'api` without flag). Any ideas?

Same traceback occurs on current Pypi release as well as primary branch of dandi-cli.

CC @bendichter 

```
Traceback (most recent call last):
  File "/home/cbaker239/miniconda3/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/cbaker239/miniconda3/lib/python3.8/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/mnt/scrap/cbaker239/dandi-cli/dandi/cli/base.py", line 109, in wrapper
    return f(*args, **kwargs)
  File "/mnt/scrap/cbaker239/dandi-cli/dandi/cli/cmd_upload.py", line 130, in upload
    upload(
  File "/mnt/scrap/cbaker239/dandi-cli/dandi/upload.py", line 48, in upload
    instance = get_instance(dandi_instance)
  File "/mnt/scrap/cbaker239/dandi-cli/dandi/utils.py", line 626, in get_instance
    api=server_info["services"]["api"]["url"],
KeyError: 'api'
```

**Comment by yarikoptic** [comment]
you could now update `dandi-cli` and try again, or just wait a bit until redirector gets restarted.
