### ISSUE TITLE
More informative error (or proper fallback to default record) when redirector is not working

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#590]
Testing #588 on 0.14.1-7-g82cf684

```shell
$> dandi download https://gui.dandiarchive.org/#/dandiset/000027
2021-04-22 15:33:21,404 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210422193320Z-1492782.log
Error: Unknown instance metadata_version: 0

$> cat /home/yoh/.cache/dandi-cli/log/20210422193320Z-1492782.log
2021-04-22T15:33:20-0400 [INFO    ] dandi 1492782:139758538225472 dandi v0.14.1+7.g82cf684, hdmf v2.3.0, pynwb v1.4.0, h5py v2.10.0
2021-04-22T15:33:20-0400 [INFO    ] dandi 1492782:139758538225472 sys.argv = ['/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi', 'download', 'https://gui.dandiarchive.org/#/dandiset/000027']
2021-04-22T15:33:20-0400 [INFO    ] dandi 1492782:139758538225472 os.getcwd() = /tmp
2021-04-22T15:33:21-0400 [WARNING ] dandi 1492782:139758538225472 Request to https://dandiarchive.org failed (502 Server Error: Bad Gateway for url: https://dandiarchive.org/server-info)
2021-04-22T15:33:21-0400 [WARNING ] dandi 1492782:139758538225472 Using hard-coded URLs
2021-04-22T15:33:21-0400 [INFO    ] dandi 1492782:139758538225472 Logs saved in /home/yoh/.cache/dandi-cli/log/20210422193320Z-1492782.log
```

<details>
<summary>with 0.14.1 we fall back to girder instance (which currently rightfully fails)</summary> 

```shell
$> dandi download https://gui.dandiarchive.org/#/dandiset/000027
2021-04-22 15:31:05,462 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210422193103Z-1492215.log
Error: Cannot download from https://gui.dandiarchive.org/#/dandiset/000027
(dev3) (dandi-py3.9-troubleshoot) 1 74859 ->1.....................................:Thu 22 Apr 2021 03:31:05 PM EDT:.
lena:/tmp
$> dandi download https://gui.dandiarchive.org/#/dandiset/000027
(dev3) (dandi-py3.9-troubleshoot) 1 74859 ->130.....................................:Thu 22 Apr 2021 03:31:12 PM EDT:.
lena:/tmp
$> cat /home/yoh/.cache/dandi-cli/log/20210422193103Z-1492215.log
2021-04-22T15:31:03-0400 [INFO    ] dandi 1492215:140596294952768 dandi v0.14.1, hdmf v2.3.0, pynwb v1.4.0, h5py v2.10.0
2021-04-22T15:31:03-0400 [INFO    ] dandi 1492215:140596294952768 sys.argv = ['/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi', 'download', 'https://gui.dandiarchive.org/#/dandiset/000027']
2021-04-22T15:31:03-0400 [INFO    ] dandi 1492215:140596294952768 os.getcwd() = /tmp
2021-04-22T15:31:04-0400 [WARNING ] dandi 1492215:140596294952768 Request to https://dandiarchive.org failed (502 Server Error: Bad Gateway for url: https://dandiarchive.org/server-info)
2021-04-22T15:31:04-0400 [WARNING ] dandi 1492215:140596294952768 Using hard-coded URLs
2021-04-22T15:31:05-0400 [WARNING ] dandi 1492215:140596294952768 Request to https://dandiarchive.org failed (502 Server Error: Bad Gateway for url: https://dandiarchive.org/server-info)
2021-04-22T15:31:05-0400 [WARNING ] dandi 1492215:140596294952768 Using hard-coded URLs
2021-04-22T15:31:05-0400 [WARNING ] dandi 1492215:140596294952768 Request to https://dandiarchive.org failed (502 Server Error: Bad Gateway for url: https://dandiarchive.org/server-info)
2021-04-22T15:31:05-0400 [WARNING ] dandi 1492215:140596294952768 Using hard-coded URLs
2021-04-22T15:31:05-0400 [WARNING ] urllib3.connection 1492215:140596294952768 Certificate did not match expected hostname: girder.dandiarchive.org. Certificate: {'subject': ((('commonName', 'dandiarchive.org'),),), 'issuer': ((('countryName', 'US'),), (('organizationName', "Let's Encrypt"),), (('commonName', 'R3'),)), 'version': 3, 'serialNumber': '03264F1E931CDECFC1C049E11A0582B971D9', 'notBefore': 'Apr 19 14:13:08 2021 GMT', 'notAfter': 'Jul 18 14:13:08 2021 GMT', 'subjectAltName': (('DNS', 'dandiarchive.org'),), 'OCSP': ('http://r3.o.lencr.org',), 'caIssuers': ('http://r3.i.lencr.org/',)}
2021-04-22T15:31:05-0400 [WARNING ] dandi 1492215:140596294952768 Failed to lookup girder information for drafts/000027

```
</details>

and it seems we fall to it here too but need version boost in the record

```
diff --git a/dandi/consts.py b/dandi/consts.py
index a10ba81..b614db3 100644
--- a/dandi/consts.py
+++ b/dandi/consts.py
@@ -87,14 +87,14 @@ known_instances = {
         None,
     ),
     "dandi": dandi_instance(
-        0,
+        1,
         "https://girder.dandiarchive.org",
         "https://gui.dandiarchive.org",
         "https://dandiarchive.org",
         None,  # publish. is gone, superseded by API which did not yet fully superseded the rest
     ),
     "dandi-api": dandi_instance(
-        1,
+        0,
         None,
         "https://gui-beta-dandiarchive-org.netlify.app",
         None,
```
but then it still fails

```
$> dandi --pdb -l debug download https://gui.dandiarchive.org/#/dandiset/000027
2021-04-22 15:39:35,091 [   DEBUG] Running a newer version (0.14.1+7.g82cf684.dirty) of dandi/dandi-cli than available (0.14.1)
2021-04-22 15:39:35,469 [   DEBUG] Caught exception 'NoneType' object has no attribute 'endswith'
2021-04-22 15:39:35,469 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210422193934Z-1493901.log
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/cli/base.py", line 105, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/cli/cmd_download.py", line 128, in download
    return download.download(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/download.py", line 79, in download
    for rec in gen_:
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/download.py", line 119, in download_generator
    server_type, _, asset_type, asset_id = parse_dandi_url(urls[0])
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/dandiarchive.py", line 346, in parse
    if not server.endswith("/"):
AttributeError: 'NoneType' object has no attribute 'endswith'

> /home/yoh/proj/dandi/dandi-cli-master/dandi/dandiarchive.py(346)parse()
-> if not server.endswith("/"):
(Pdb) p server
None
(Pdb) 
```

**Comment by yarikoptic** [comment]
is that something we might still observe with #588 merged? if so - should still be addressed

**Comment by jwodder** [comment]
@yarikoptic I don't believe so.
