### ISSUE TITLE
can't upload file/asset if metadata "extraction" fails (even if `--validation ignore`)

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#661]
with 0.19.0+31.g02ee314 , `upload` of a file where metadata extraction fails would not upload at all.
In my case it was on a dummy old nwb we have in 000027 and 29:
```
(git-annex)lena:~/proj/dandi/dandisets/000029[master]git
$> dandi upload --validation ignore --existing force sub-RAT123/sub-RAT123.nwb
2021-06-09 17:15:48,403 [    INFO] Found 1 files to consider
PATH                      SIZE       ERRORS     UPLOAD STATUS                MESSAGE                      
sub-RAT123/sub-RAT123.nwb 18.8 kB       1              skipped               failed to extract metadata...
Summary:                  18.8 kB 1 with errors        1 skipped             1 failed to extract metada...
2021-06-09 17:15:48,802 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210609211546Z-1677599.log
```
and log gave gory details
```
2021-06-09T17:15:46-0400 [INFO    ] dandi 1677599:140096533518144 dandi v0.19.0+31.g02ee314, hdmf v2.3.0, pynwb v1.4.0, h5py v2.10.0
2021-06-09T17:15:46-0400 [INFO    ] dandi 1677599:140096533518144 sys.argv = ['/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi', 'upload', '--validation', 'ignore', '--existing', 'force', 'sub-RAT123/sub-RAT123.nwb']
2021-06-09T17:15:46-0400 [INFO    ] dandi 1677599:140096533518144 os.getcwd() = /home/yoh/proj/dandi/dandisets/000029
2021-06-09T17:15:48-0400 [INFO    ] dandi 1677599:140096533518144 Found 1 files to consider
2021-06-09T17:15:48-0400 [ERROR   ] dandi 1677599:140096393844480 Failed to extract metadata from sub-RAT123/sub-RAT123.nwb
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/upload.py", line 245, in process_path
    asset_metadata = nwb2asset(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 551, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 601, in metadata2asset
    bare_dict = extract_model(models.BareAsset, metadata).json_dict()
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 229, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 313, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 282, in extract_session
    models.Session(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Session
name
  none is not an allowed value (type=type_error.none.not_allowed)
2021-06-09T17:15:48-0400 [INFO    ] dandi 1677599:140096533518144 Logs saved in /home/yoh/.cache/dandi-cli/log/20210609211546Z-1677599.log
```

so session is not there and that causes `nwb2asset` to kaboom.  I guess we could take it as a feature but I believe it is a regression (didn't check yet) from previous behavior where we did allow to upload if `--validation ignore` or alike. WDYT @satra ?

**Comment by yarikoptic** [comment]
FWIW, we can still force the hand with `--allow-any-path` option of DANDI_DEVEL mode.
```
$> DANDI_DEVEL=1 dandi upload --validation ignore --existing force --allow-any-path sub-RAT123/sub-RAT123.nwb 
2021-06-09 17:23:57,655 [    INFO] Found 1 files to consider
PATH                      SIZE       ERRORS     UPLOAD STATUS                       MESSAGE                       
sub-RAT123/sub-RAT123.nwb 18.8 kB       1              done                         exists (older) - reuploading  
Summary:                  18.8 kB 1 with errors        1 done                       1 exists (older) - reuploading
2021-06-09 17:23:58,578 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210609212355Z-1680743.log
(dev3) 1 15121.....................................:Wed 09 Jun 2021 05:23:58 PM EDT:.
(git-annex)lena:~/proj/dandi/dandisets/000029[master]git-annex
$> cat /home/yoh/.cache/dandi-cli/log/20210609212355Z-1680743.log
2021-06-09T17:23:55-0400 [INFO    ] dandi 1680743:139844654200640 dandi v0.19.0+31.g02ee314, hdmf v2.3.0, pynwb v1.4.0, h5py v2.10.0
2021-06-09T17:23:55-0400 [INFO    ] dandi 1680743:139844654200640 sys.argv = ['/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi', 'upload', '--validation', 'ignore', '--existing', 'force', '--allow-any-path', 'sub-RAT123/sub-RAT123.nwb']
2021-06-09T17:23:55-0400 [INFO    ] dandi 1680743:139844654200640 os.getcwd() = /home/yoh/proj/dandi/dandisets/000029
2021-06-09T17:23:57-0400 [INFO    ] dandi 1680743:139844654200640 Found 1 files to consider
2021-06-09T17:23:58-0400 [ERROR   ] dandi 1680743:139844514494208 Failed to extract metadata from sub-RAT123/sub-RAT123.nwb
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/upload.py", line 245, in process_path
    asset_metadata = nwb2asset(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 551, in nwb2asset
    asset = metadata2asset(metadata)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 601, in metadata2asset
    bare_dict = extract_model(models.BareAsset, metadata).json_dict()
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 229, in extract_model
    value = kwargs.get(field, extract_field(field, metadata))
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 313, in extract_field
    return FIELD_EXTRACTORS[field](metadata)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/metadata.py", line 282, in extract_session
    models.Session(
  File "pydantic/main.py", line 400, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Session
name
  none is not an allowed value (type=type_error.none.not_allowed)
2021-06-09T17:23:58-0400 [INFO    ] dandi 1680743:139844514494208 sub-RAT123/sub-RAT123.nwb: Asset successfully uploaded
2021-06-09T17:23:58-0400 [INFO    ] dandi 1680743:139844654200640 Logs saved in /home/yoh/.cache/dandi-cli/log/20210609212355Z-1680743.log
```

**Comment by satra** [comment]
checking on this.
