### ISSUE TITLE
Errors uploading to staging

### ISSUE THREAD

**Issue by dchiquito** [dandi/dandi-cli#677]
When I try to upload files to staging, the upload succeeds, but this error is printed out from the CLI:
```
(dandi-cli) daniel.chiquito@krs-3081:~/Downloads/dandi/000002$ DANDI_DEVEL=1 dandi upload -i dandi-staging -e force sub-anm372909/sub-anm372909_ses-20170522.nwb 
2021-06-21 15:58:04,229 [    INFO] Found 1 files to consider
PATH                                         SIZE    ERRORS UPLOAD STATUS                MESSAGE
sub-anm372909/sub-anm372909_ses-20170522.nwb 5.7 MB    0           producing asset              


ERROR: 1 asynchronous worker failed

Producing value for row ('sub-anm372909/sub-anm372909_ses-20170522.nwb',) failed:
Traceback (most recent call last):
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 270, in _print_async_exceptions
    future.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 462, in async_fn
    self._write_async_result(id_vals, cols, i)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 94, in wrapped
    return method(self, *args, **kwds)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 421, in _write_async_result
    self._write(result)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 339, in _write
    self._write_fn(row, style)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/interface.py", line 354, in _write_update
    content, status, summary = self._content.update(row, style)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/common.py", line 858, in update
    content, status = super(ContentWithSummary, self).update(row, style)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/common.py", line 825, in update
    line, adjusted = self.fields.render(row, style)
  File "/home/daniel.chiquito/envs/dandi-cli/lib/python3.8/site-packages/pyout/common.py", line 625, in render
    if hidden[c] == "if_missing" and not isinstance(val, Nothing):
KeyError: 'asset'

2021-06-21 15:58:04,981 [    INFO] Logs saved in /home/daniel.chiquito/.cache/dandi-cli/log/20210621195801Z-11551.log
```

**Comment by satra** [comment]
@dchiquito - i'm pretty sure it's because that dataset doesn't pass validation because it uses a really old version. for testing you could add `--validation skip` or use a subset of data from a more recent dandiset from the production server.

**Comment by yarikoptic** [comment]
wow -- some fun one deeply entrenched into `pyout`.  meanwhile, you can add `--devel-debug` so it would not use pyout and thus not even parallelize and only spit out the records to the screen.  Please share those for your upload here: that would then help to see what freaks pyout out ;-) 

meanwhile -- I will try to replicate and see if could be easily fixed on dandi-cli side or might need pyout tuning

**Comment by yarikoptic** [comment]
the crash issue -- please check pyout version you have. I have `0.7.0` and without skipping validation , as @satra correctly hinted on, it seems to "work" (although output screwed up but it doesn't crash):
```
$> DANDI_DEVEL=1 dandi upload -i dandi-staging -e force sub-anm372909/sub-anm372909_ses-20170522.nwb 
Please provide API Key for dandi-staging: d7bb3970ac4802f4d06c0ef4fd7f5720b05423eb
2021-06-21 19:39:58,601 [    INFO] Found 1 files to consider
PATH                                         SIZE    ERRORS UPLOAD STATUS           MESSAGE
sub-anm372909/sub-anm372909_ses-20170522.nwb 5.7 MB                pre-validating          
Summary:                                     5.7 MB                1 pre-validating        
PATH                                     SIZE       ERRORS     UPLOAD STATUS           MESSAGE            ...372909/sub-anm372909_ses-20170522.nwb 5.7 MB        4              skipped          failed validation  
Summary:                                 5.7 MB  1 with errors        1 skipped        1 failed validation
2021-06-21 19:39:58,847 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210621233945Z-3478926.log

```
and running ignoring validation still doesn't crash but shows the new unexpected `asset` field:
```
lena:/tmp/000018
$> DANDI_DEVEL=1 dandi upload -i dandi-staging -e force --validation ignore sub-anm372909/sub-anm372909_ses-20170522.nwb
2021-06-21 19:40:22,195 [    INFO] Found 1 files to consider
PATH                                         SIZE      ERRORS     UPLOAD STATUS MESSAGE ASSET                                                                                                                        
sub-anm372909/sub-anm372909_ses-20170522.nwb 5.7 MB       4              done           client=<dandi.dandiapi.DandiAPIClient object at 0x7fb600811400> dandiset_id='000018' version_id='draft' identifier='e2ebde...
Summary:                                     5.7 MB 1 with errors        1 done                                                                                                                                      
2021-06-21 19:40:23,435 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20210621234019Z-3479080.log
```
but again -- doesn't crash.  I filed a dedicated issue for the "unexpected" `asset`  field: https://github.com/dandi/dandi-cli/issues/678
