### ISSUE TITLE
bids validation -- report error on invalid json of dataset_description.json

### ISSUE THREAD

**Issue by yarikoptic** [dandi/dandi-cli#988]
happened due to https://github.com/dandisets/000058/issues/1 .

```
$> dandi validate-bids derivatives/fitparmms/Siemens/sub-MITU01/ses-MR/anat/*nii.gz
2022-04-28 17:50:00,802 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220428214959Z-1778025.log
Error: Expecting ',' delimiter: line 13 column 3 (char 172)
```
and even looking into that .log file it is not clear on what is going on, in what file etc.  Had to go to pdb to figure it out
```
lena:/tmp/dandisets/000058
$> dandi --pdb validate-bids derivatives/fitparmms/Siemens/sub-MITU01/ses-MR/anat/*nii.gz   
2022-04-28 17:50:36,028 [    INFO] Logs saved in /home/yoh/.cache/dandi-cli/log/20220428215034Z-1778174.log
Traceback (most recent call last):
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/bin/dandi", line 33, in <module>
    sys.exit(load_entry_point('dandi', 'console_scripts', 'dandi')())
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/venvs/dev3/lib/python3.9/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/cli/base.py", line 102, in wrapper
    return f(*args, **kwargs)
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/cli/cmd_validate.py", line 33, in validate_bids
    validate_bids_(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/validate.py", line 36, in validate_bids
    return validate_bids_(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/bids_validator_xs.py", line 699, in validate_bids
    bids_schema_dir = select_schema_dir(
  File "/home/yoh/proj/dandi/dandi-cli-master/dandi/bids_validator_xs.py", line 614, in select_schema_dir
    dataset_info = json.load(f)
  File "/usr/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 13 column 3 (char 172)

> /usr/lib/python3.9/json/decoder.py(353)raw_decode()
-> obj, end = self.scan_once(s, idx)
(Pdb) up
```

ideally should have reported an error 27 JSON_INVALID from "Validator issues" instead of just crash

**Comment by TheChymera** [comment]
Solved by: https://github.com/dandi/dandi-cli/pull/1050


https://github.com/dandi/dandi-cli/blob/468e39c9c3f7962e5078e9bdc4b6ad1f16fa4ee8/dandi/support/bids/validator.py#L625-L633

**Comment by TheChymera** [comment]
closing since PR that fixed it is in.
